"""Render results.json into the paper's generated tables."""

from __future__ import annotations

import argparse
import json
from pathlib import Path

CONDITIONS = ("raw", "naive", "emotion", "affect", "scene", "shuffled")


def _fmt(x) -> str:
    return "n/a" if x is None or (isinstance(x, float) and x != x) else f"{x:.3f}"


def _rho(m: dict, key: str) -> str:
    """Correlation with its bootstrap CI when available, never a bare 3-decimal."""
    rho = m.get(key)
    ci = m.get(f"{key}_ci")
    if ci and not (isinstance(ci[0], float) and ci[0] != ci[0]):
        return f"{_fmt(rho)} [{ci[0]:.2f}, {ci[1]:.2f}]"
    return _fmt(rho)


def _shuffled_note(metrics: dict) -> str:
    """Circularity check: does any conditioning tier beat the shuffled-label null?"""
    parts = []
    for cond in ("naive", "emotion", "affect"):
        sc = (metrics.get(cond) or {}).get("shuffled_control")
        if sc:
            parts.append(f"{cond} p={sc['p_value']:.2f}")
    if not parts:
        return ""
    null = (metrics.get("emotion") or metrics.get("affect") or {}).get("shuffled_control", {})
    base = f" (null mean {null['null_mean']:.3f})" if null else ""
    return (
        "**Shuffled-label control:** one-sided permutation test of recovery vs randomly "
        f"reassigned target emotions{base}: {', '.join(parts)}. A p near 1 means recovery is "
        "indistinguishable from the circularity baseline, i.e. not above chance label agreement."
    )


def metrics_table(metrics: dict) -> str:
    head = "| Condition | Accuracy [95% CI] | Macro-F1 | Valence ρ†‡ | Arousal ρ†‡ | CLIP-T | n |"
    rule = "|" + "---|" * 7
    lines = [head, rule]
    for cond in CONDITIONS:
        m = metrics.get(cond)
        if not m:
            continue
        lo, hi = m["accuracy_ci"]
        acc = f"{m['accuracy']:.3f} [{lo:.3f}, {hi:.3f}]"
        lines.append(
            f"| {cond} | {acc} | {_fmt(m['macro_f1'])} | {_rho(m, 'valence_rho')} | "
            f"{_rho(m, 'arousal_rho')} | {_fmt(m['clip_t'])} | {m['n']} |"
        )
    chance = metrics.get("chance")
    base = metrics.get("raw", {}).get("majority_baseline")
    if chance is not None:
        note = f"\nChance = {chance:.3f} (1/7)"
        if base is not None:
            note += f"; majority-class baseline = {base:.3f}"
        note += (
            ". A probe collapsed onto one label scores here, so recovery is only "
            "informative *above* it."
        )
        lines.append(note)
    health = metrics.get("probe_health")
    if health:
        lines.append(
            f"**Probe health:** the probe used {health['distinct_labels']}/{health['n_labels']} "
            f"emotion labels across the conditioning tiers, predicting "
            f"'{health['majority_label']}' for {health['majority_rate']:.0%} of items, every "
            "recovery number must be read against this degeneracy."
        )
    shuffled = _shuffled_note(metrics)
    if shuffled:
        lines.append(shuffled)
    lines.append(
        "† On neutral content the intended valence/arousal is the per-emotion prior, so these "
        "correlations reflect between-emotion separation, not within-emotion grounding."
    )
    lines.append(
        "‡ ρ is shown with its bootstrap 95% CI; at small n the interval spans most of [-1, 1], "
        "so the point estimate should not be over-read."
    )
    return "\n".join(lines)


def contrasts_table(contrasts: dict) -> str:
    head = "| Contrast | Δ accuracy | 95% CI | p |"
    rule = "|" + "---|" * 4
    lines = [head, rule]
    for name, c in contrasts.items():
        ci = f"[{c['ci_low']:.3f}, {c['ci_high']:.3f}]"
        label = name.replace("_", " ")
        lines.append(f"| {label} | {c['mean_diff']:+.3f} | {ci} | {c['p_value']:.3f} |")
    return "\n".join(lines)


def render(results: dict) -> str:
    parts = [
        "<!-- generated by scripts/report.py; do not edit by hand -->",
        "**Table 1.** Affect recovery by conditioning condition.",
        "",
        metrics_table(results["metrics"]),
        "",
        "**Table 2.** Paired contrasts on per-item recovery (bootstrap).",
        "",
        contrasts_table(results["contrasts"]),
        "",
    ]
    return "\n".join(parts) + "\n"


def inject(paper_path: str | Path, tables: str) -> bool:
    """Replace the content between the TABLES markers in the paper."""
    path = Path(paper_path)
    if not path.exists():
        return False
    text = path.read_text()
    start, end = "<!--TABLES-->", "<!--/TABLES-->"
    if start not in text or end not in text:
        return False
    head = text.split(start)[0]
    tail = text.split(end, 1)[1]
    path.write_text(f"{head}{start}\n{tables}{end}{tail}")
    return True


def main() -> None:
    parser = argparse.ArgumentParser(description="Render results as markdown tables")
    parser.add_argument("--results", default="results/paper/results.json")
    parser.add_argument("--out", default="paper/tables.md")
    parser.add_argument("--paper", default="paper/paper.md", help="inject tables into this file")
    args = parser.parse_args()

    results = json.loads(Path(args.results).read_text())
    table = render(results)
    Path(args.out).write_text(table)
    if inject(args.paper, table):
        print(f"Injected tables into {args.paper}")
    print(table)


if __name__ == "__main__":
    main()
