"""Render results.json into the paper's generated tables."""

from __future__ import annotations

import argparse
import json
from pathlib import Path

CONDITIONS = ("raw", "emotion", "affect", "scene")


def _fmt(x) -> str:
    return "–" if x is None or (isinstance(x, float) and x != x) else f"{x:.3f}"


def metrics_table(metrics: dict) -> str:
    head = "| Condition | Accuracy [95% CI] | Macro-F1 | Valence ρ | Arousal ρ | CLIP-T | n |"
    rule = "|" + "---|" * 7
    lines = [head, rule]
    for cond in CONDITIONS:
        m = metrics.get(cond)
        if not m:
            continue
        lo, hi = m["accuracy_ci"]
        acc = f"{m['accuracy']:.3f} [{lo:.3f}, {hi:.3f}]"
        lines.append(
            f"| {cond} | {acc} | {_fmt(m['macro_f1'])} | {_fmt(m.get('valence_rho'))} | "
            f"{_fmt(m.get('arousal_rho'))} | {_fmt(m['clip_t'])} | {m['n']} |"
        )
    chance = metrics.get("chance")
    if chance is not None:
        lines.append(f"\nChance accuracy = {chance:.3f} (1/7).")
    return "\n".join(lines)


def contrasts_table(contrasts: dict) -> str:
    head = "| Contrast | Δ accuracy | 95% CI | p |"
    rule = "|" + "---|" * 4
    lines = [head, rule]
    for name, c in contrasts.items():
        ci = f"[{c['ci_low']:.3f}, {c['ci_high']:.3f}]"
        label = name.replace("_", " ")
        lines.append(f"| {label} | {c['mean_diff']:+.3f} | {ci} | {c['p_value']:.3f} |")
    return "\n".join(lines)


def render(results: dict) -> str:
    parts = [
        "<!-- generated by scripts/report.py; do not edit by hand -->",
        "**Table 1.** Affect recovery by conditioning condition.",
        "",
        metrics_table(results["metrics"]),
        "",
        "**Table 2.** Paired contrasts on per-item recovery (bootstrap).",
        "",
        contrasts_table(results["contrasts"]),
        "",
    ]
    return "\n".join(parts) + "\n"


def inject(paper_path: str | Path, tables: str) -> bool:
    """Replace the content between the TABLES markers in the paper."""
    path = Path(paper_path)
    if not path.exists():
        return False
    text = path.read_text()
    start, end = "<!--TABLES-->", "<!--/TABLES-->"
    if start not in text or end not in text:
        return False
    head = text.split(start)[0]
    tail = text.split(end, 1)[1]
    path.write_text(f"{head}{start}\n{tables}{end}{tail}")
    return True


def main() -> None:
    parser = argparse.ArgumentParser(description="Render results as markdown tables")
    parser.add_argument("--results", default="results/results.json")
    parser.add_argument("--out", default="paper/tables.md")
    parser.add_argument("--paper", default="paper/paper.md", help="inject tables into this file")
    args = parser.parse_args()

    results = json.loads(Path(args.results).read_text())
    table = render(results)
    Path(args.out).write_text(table)
    if inject(args.paper, table):
        print(f"Injected tables into {args.paper}")
    print(table)


if __name__ == "__main__":
    main()
